[build] 
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.55.5" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.5" # if older, use format: 0.53 (no trailing zero)

[force to https]
https://jack.rbind.io/*  https://jack.rbind.io/:splat  301!
http://jack.rbind.io/*   https://jack.rbind.io/:splat  301!
http://jack.rbind.io/*   https://jack.rbind.io/:splat  301!

# Fix annoying effect of slug on bundled pages
/post/:year-:month-:date-:slug/:slug/         /post/:year-:month-:date-:slug/